routes/web.php
<?php
// use Analytics;
use Spatie\Analytics\Period;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
| 
*/
Route::get('/', function () {
    return view('home');
    })->middleware('SharedVariables');
Route::get('/welcome','HomeController@welcome_admin');
Route::get('/welcome_error','HomeController@welcome_error');



Auth::routes();


if ((Request::segment('1') != 'admin') && (Request::segment('1') == 'en')||(Request::segment('1') == 'ar')) {
	Route::group(['prefix'=>'{lang?}','middleware'=>['lang','SharedVariables']],function()
   {
		Route::get('home', 'HomeController@index');
		Route::get('course/{id}', 'FrontController@course');
		Route::get('type/{id}', 'FrontController@type');
		Route::get('branch/{id}', 'FrontController@branch');
		Route::get('news/{id}', 'FrontController@news');
		Route::get('events/{id}', 'FrontController@events');
		Route::get('course_schedule/{id}', 'FrontController@course_schedule');
		Route::get('course_all/{id}', 'FrontController@course_all');
		Route::get('course_reservation/{id}/{course_id}', 'FrontController@course_reservation')->middleware('auth');
		Route::post('confirm_reservation/{id}/{course_id}', 'FrontController@confirm_reservation')->middleware('auth');

		Route::post('confirm__private_reservation/{id}/{course_id}', 'FrontController@confirm__private_reservation')->middleware('auth');
		Route::post('confirm__company_reservation/{id}/{course_id}', 'FrontController@confirm__company_reservation')->middleware('auth');
	 
		Route::get('register_page', 'Auth\RegisterController@register');
	    Route::post('register_success', 'Auth\RegisterController@create_new');
		Route::get('login_page', 'Auth\LoginController@login_page');
		Route::post('login_success', 'Auth\LoginController@check_login');
		Route::get('view_profile', 'UserController@view_profile')->middleware('auth');
		Route::patch('edit_profile/{id}', 'UserController@edit_profile')->middleware('auth');
		Route::get('update_password', 'UserController@update_password')->middleware('auth');
		Route::patch('edit_password/{id}', 'UserController@edit_password')->middleware('auth');
		Route::get('view_course_users', 'UserController@view_user_course')->middleware('auth');
		Route::get('course_dates','UserController@course_dates');
	    Route::get('course_matirial','UserController@course_matirial');
	    Route::get('course_feedback','UserController@course_feedback');
	    Route::post('feedback_course_store', 'UserController@feedback_course_store');
		Route::get('download/{id}', 'UserController@getDownload');
		Route::get('view_kill_sheet', 'UserController@view_kill_sheet');
		Route::get('add_kill_sheet', 'UserController@add_kill_sheet');
		Route::get('applay', 'UserController@applay');
		Route::post('applay_store', 'UserController@applay_store');
		Route::post('store_kill_sheet', 'UserController@store_kill_sheet');
		Route::get('del/{id}', 'UserController@del');
		Route::get('edit_kill_sheet', 'UserController@edit_kill_sheet');
		Route::get('date/{id}/{schedule}', 'UserController@date');
		Route::get('kill_can/', 'UserController@kill_can');
		Route::post('kill_can_store/', 'UserController@kill_can_store');
		Route::get('view_kill_can', 'UserController@view_kill_can');
		Route::get('user_rate', 'UserController@user_rate');
		Route::post('contact_us', 'FrontController@contact');
		Route::get('content', 'FrontController@content');
		Route::get('more', 'FrontController@more');
		Route::post('subscribe', 'FrontController@subscribe');
		Route::get('subscribe_course', 'FrontController@subscribe_course');
		Route::post('subscribe_store', 'FrontController@subscribe_store');
		Route::get('course_branch', 'FrontController@get_branch');
		Route::get('not_apply', 'FrontController@not_apply');
		Route::get('instructor_candidate_attendances', 'UserController@instructor_candidate_attendances'); 
		Route::post('store_instructor_candidate_attendances', 'UserController@store_instructor_candidate_attendances');
		Route::get('check_right/', 'UserController@check_right');
		Route::get('check_false/', 'UserController@check_false');
		Route::get('{page}', 'FrontController@page');


   });
	
}
elseif(Request::segment('1') == 'admin')
{
	Route::get('admin/Home/view_page_popup','ViewpopupController@Viewpop')->middleware('AuthAdmin')->middleware('IsAdmin');
	Route::get('admin/user_category','AccountingController@user_category')->middleware('AuthAdmin')->middleware('IsAdmin');
	Route::group(['prefix'=>'admin','middleware'=>['AuthAdmin','IsAdmin','Permiation']],function()
    {
		Route::get('/','HomeController@admin');
		
		Route::get('/hotels/delete','HotelController@delete');
		Route::resource('/hotels','HotelController');
		Route::get('hotels/trash/{id}/{trash}','HotelController@trash');
		Route::get('/restaurants/delete','RestaurantController@delete');
		Route::resource('/restaurants','RestaurantController');
		Route::get('restaurants/trash/{id}/{trash}','RestaurantController@trash');
		Route::get('/users/delete','UserController@delete');
		Route::resource('/users','UserController');
		Route::get('users/trash/{id}/{trash}','UserController@trash');
		Route::get('users/exams/{id}','UserController@user_exams');

		Route::get('/subject_categories/delete','SubjectCategoryController@delete');
		Route::resource('/subject_categories','SubjectCategoryController');
		Route::get('subject_categories/trash/{id}/{trash}','SubjectCategoryController@trash');

		Route::get('/subjects/delete','SubjectController@delete');
		Route::resource('/subjects','SubjectController');
		Route::get('subjects/trash/{id}/{trash}','SubjectController@trash');

		Route::get('/instructors/delete','InstructorController@delete');
		Route::resource('/instructors','InstructorController');
		Route::get('instructors/trash/{id}/{trash}','InstructorController@trash');
		Route::get('instructors/courses/{id}/{type}','InstructorController@instructor_course');
		Route::get('course/subscribe_course','CoursesController@subscribe_course');
		Route::post('/course/subscrib_course_save','CoursesController@subscrib_course_save');

		Route::get('course/subscribe_all','CoursesController@subscribe_all');
		Route::post('/course/subscrib_all_save','CoursesController@subscrib_all_save');
		Route::get('subscribe_all_web','SubscriberController@subscribe_all_web');
		Route::post('/subscrib_all_save','SubscriberController@subscrib_all_save');
		
		Route::get('/course/delete','CoursesController@delete');
		Route::resource('/course','CoursesController');
		Route::get('course/trash/{id}/{trash}','CoursesController@trash');
		Route::get('/course/schedule_add/{id}','CoursesController@schedule_add');
		Route::post('/course/schedule_save/{id}','CoursesController@schedule_save');
		Route::get('/course/schedule_view/{id}','CoursesController@schedule_view');
		Route::get('/course/schedule_edit/{id}','CoursesController@schedule_edit');
	    Route::PATCH('/course/schedule_update/{id}','CoursesController@schedule_update');
	    Route::get('course/subscribe/{id}','CoursesController@subscribe');
	    Route::get('/course/date_attendance/{id}/{date}','CoursesController@date_attendance');


		Route::get('/exam/delete','ExamController@delete');
		Route::resource('/exam','ExamController');
		Route::get('exam/trash/{id}/{trash}','ExamController@trash');
		Route::get('/feedback/{type}','FeedbackController@index');
		Route::get('/pages/delete','PagesController@delete');
		Route::resource('/pages','PagesController');
		Route::get('pages/trash/{id}/{trash}','PagesController@trash');
		Route::resource('/news','NewsController');
		Route::resource('/events','EventsController');

		Route::get('/gallery/delete','GalleryController@delete');
		Route::resource('/gallery','GalleryController');
		Route::get('gallery/trash/{id}/{trash}','GalleryController@trash');
		Route::get('gallery/add/{id}/{table}','GalleryController@add');
		Route::post('gallery/add_store/{id}/{table}','GalleryController@add_store');

		Route::get('/accordion/delete','AccordionController@delete');
		Route::resource('/accordion','AccordionController');
		Route::get('accordion/trash/{id}/{trash}','AccordionController@trash');
		Route::get('accordion/create/{id}','AccordionController@create');
		Route::post('accordion/store/{id}','AccordionController@store');

		Route::get('/company_account/delete','CompanyAccountController@delete');
		Route::resource('/company_account','CompanyAccountController');
		Route::get('company_account/trash/{id}/{trash}','CompanyAccountController@trash');

		Route::get('/reservations/delete','ReservationController@delete');
		Route::resource('/reservations','ReservationController');
		Route::get('reservations/trash/{id}/{trash}','ReservationController@trash');
		Route::get('reservations/status/{id}/{trash}','ReservationController@status');
		
		


	    Route::get('private_reservations/search','PrivateController@search');
	    Route::get('private_reservations/course','PrivateController@course');
		Route::get('/private_reservations/delete','PrivateController@delete');
		Route::resource('/private_reservations','PrivateController');
		Route::get('private_reservations/trash/{id}/{trash}','PrivateController@trash');
		

		Route::get('company_reservations/company_search','CompanyreservationController@company_search');
		Route::get('/company_reservations/delete','CompanyreservationController@delete');
		Route::resource('/company_reservations','CompanyreservationController');
		Route::get('company_reservations/trash/{id}/{trash}','CompanyreservationController@trash');
		Route::get('company_reservations/status/{id}/{trash}','CompanyreservationController@status');

resources/views/back/sub_cate/add.blade.php
@extends('layout.layout')
@section('content')

<div class="m-grid__item m-grid__item--fluid m-wrapper">

					<!-- BEGIN: Subheader -->
					<div class="m-subheader ">
						<div class="d-flex align-items-center">
							<div class="mr-auto">
								<h3 class="m-subheader__title m-subheader__title--separator">
									Add New Sub_Category
								</h3>
								<ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
									<li class="m-nav__item m-nav__item--home">
										<a href="#" class="m-nav__link m-nav__link--icon">
											<i class="m-nav__link-icon la la-home"></i>
										</a>
									</li>
									<li class="m-nav__separator">
										-
									</li>
									<li class="m-nav__item">
										<a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												All_Sub_Category
											</span>
										</a>
									</li>
									<li class="m-nav__separator">
										-
									</li>
									<li class="m-nav__item">
										<a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												Add Sub_Category
											</span>
										</a>
									</li>
									
									
								</ul>
							</div>
							
							<div>
								
								<div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push" data-dropdown-toggle="hover" aria-expanded="true">
									<a href="#" class="m-portlet__nav-link btn btn-lg btn-secondary  m-btn m-btn--outline-2x m-btn--air m-btn--icon m-btn--icon-only m-btn--pill  m-dropdown__toggle">
										<i class="la la-plus m--hide"></i>
										<i class="la la-ellipsis-h"></i>
									</a>
									<div class="m-dropdown__wrapper">
										<span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
										<div class="m-dropdown__inner">
											<div class="m-dropdown__body">
												<div class="m-dropdown__content">
													<ul class="m-nav">
														<li class="m-nav__section m-nav__section--first m--hide">
															<span class="m-nav__section-text">
																Quick Actions
															</span>
														</li>
														<li class="m-nav__item">
															<a href="" class="m-nav__link">
																<i class="m-nav__link-icon flaticon-share"></i>
																<span class="m-nav__link-text">
																	Activity
																</span>
															</a>
														</li>
														<li class="m-nav__item">
															<a href="" class="m-nav__link">
																<i class="m-nav__link-icon flaticon-chat-1"></i>
																<span class="m-nav__link-text">
																	Messages
																</span>
															</a>
														</li>
														<li class="m-nav__item">
															<a href="" class="m-nav__link">
																<i class="m-nav__link-icon flaticon-info"></i>
																<span class="m-nav__link-text">
																	FAQ
																</span>
															</a>
														</li>
														<li class="m-nav__item">
															<a href="" class="m-nav__link">
																<i class="m-nav__link-icon flaticon-lifebuoy"></i>
																<span class="m-nav__link-text">
																	Support
																</span>
															</a>
														</li>
														<li class="m-nav__separator m-nav__separator--fit"></li>
														<li class="m-nav__item">
															<a href="#" class="btn btn-outline-danger m-btn m-btn--pill m-btn--wide btn-sm">
																Submit
															</a>
														</li>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- END: Subheader -->
					<div class="m-content">
						<div class="row">
							<div class="col-lg-12">
								<!--begin::Portlet-->
								<div class="m-portlet">
									<div class="m-portlet__head">
										<div class="m-portlet__head-caption">
											<div class="m-portlet__head-title">
												<span class="m-portlet__head-icon m--hide">
													<i class="la la-gear"></i>
												</span>
												<h3 class="m-portlet__head-text">
													Add new sub_cat
												</h3>
											</div>
										</div>
									</div>
									<!--begin::Form-->
									
									<form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" method="POST" action="{{route('subject_categories.store')}}" enctype="multipart/form-data">
                       				 {{ csrf_field() }} 
										<div class="m-portlet__body">
											<div class="form-group m-form__group row">
													<div class="col-lg-6">
													<label>
														Name_EN:
													</label>
													<input type="text" class="form-control m-input" placeholder="Enter name" name="name_en" required>
													<span class="m-form__help">
														Please enter name_en
													</span>
												</div>
												<div class="col-lg-6">
													<label>
														Name_AR:
													</label>
													<input type="text" class="form-control m-input" placeholder="Enter name" name="name_ar" required>
													<span class="m-form__help">
														Please enter name_ar
													</span>
												</div>

												<div class="col-lg-6">
													<label>
														Image:
													</label>
													<input type="file" class="form-control m-input" placeholder="Enter your image" name="image" required>
													<span class="m-form__help">
														Please upload your image
													</span>
												</div>

												<div class="col-lg-6">
													<label class="">
														Type
													</label>
													<div class="m-input-icon m-input-icon--right">
														<select name="type_id" id="parent_category" class="form-control m-input  m-input--square" required>
						                                    @foreach ($types as $type )
						                                        <option value="{{ $type->id }}">{{ $type->name_en.'_'.$type->name_ar }}</option>
						                                    @endforeach
						                                </select>
													</div>
													<span class="m-form__help">
														Please enter Type
													</span>
												</div>
												
												
											</div>
											
											
										</div>
										<div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
											<div class="m-form__actions m-form__actions--solid">
												<div class="row">
													<div class="col-lg-6">
														<button type="Submit" class="btn btn-brand">
															Save
														</button>
														<a type="button" class="btn btn-default" href="{{route('subject_categories.index')}}" style="color: #716aca;">
															Cancel
														</a>
													</div>
													<div class="col-lg-6 m--align-right">
														<button type="reset" class="btn btn-danger">
															Delete
														</button>
													</div>
												</div>
											</div>
										</div>
									</form>
									<!--end::Form-->
								</div>
								<!--end::Portlet-->
							</div>
						</div>
					</div>
				</div>



@endsection

resources/views/back/sub_cate/edit.blade.php
@extends('layout.layout')
@section('content')

<div class="m-grid__item m-grid__item--fluid m-wrapper">

					<!-- BEGIN: Subheader -->
					<div class="m-subheader ">
						<div class="d-flex align-items-center">
							<div class="mr-auto">
								<h3 class="m-subheader__title m-subheader__title--separator">
									edit {{$sub_cat->name}}  Sub_category
								</h3>
								<ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
									<li class="m-nav__item m-nav__item--home">
										<a href="#" class="m-nav__link m-nav__link--icon">
											<i class="m-nav__link-icon la la-home"></i>
										</a>
									</li>
									<li class="m-nav__separator">
										-
									</li>
									<li class="m-nav__item">
										<a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												All_Sub_category
											</span>
										</a>
									</li>
									<li class="m-nav__separator">
										-
									</li>
									<li class="m-nav__item">
										<a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												add sub_cate
											</span>
										</a>
									</li>
									
									
								</ul>
							</div>
							
							<div>
								
								<div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push" data-dropdown-toggle="hover" aria-expanded="true">
									<a href="#" class="m-portlet__nav-link btn btn-lg btn-secondary  m-btn m-btn--outline-2x m-btn--air m-btn--icon m-btn--icon-only m-btn--pill  m-dropdown__toggle">
										<i class="la la-plus m--hide"></i>
										<i class="la la-ellipsis-h"></i>
									</a>
									<div class="m-dropdown__wrapper">
										<span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
										<div class="m-dropdown__inner">
											<div class="m-dropdown__body">
												<div class="m-dropdown__content">
													<ul class="m-nav">
														<li class="m-nav__section m-nav__section--first m--hide">
															<span class="m-nav__section-text">
																Quick Actions
															</span>
														</li>
														<li class="m-nav__item">
															<a href="" class="m-nav__link">
																<i class="m-nav__link-icon flaticon-share"></i>
																<span class="m-nav__link-text">
																	Activity
																</span>
															</a>
														</li>
														<li class="m-nav__item">
															<a href="" class="m-nav__link">
																<i class="m-nav__link-icon flaticon-chat-1"></i>
																<span class="m-nav__link-text">
																	Messages
																</span>
															</a>
														</li>
														<li class="m-nav__item">
															<a href="" class="m-nav__link">
																<i class="m-nav__link-icon flaticon-info"></i>
																<span class="m-nav__link-text">
																	FAQ
																</span>
															</a>
														</li>
														<li class="m-nav__item">
															<a href="" class="m-nav__link">
																<i class="m-nav__link-icon flaticon-lifebuoy"></i>
																<span class="m-nav__link-text">
																	Support
																</span>
															</a>
														</li>
														<li class="m-nav__separator m-nav__separator--fit"></li>
														<li class="m-nav__item">
															<a href="#" class="btn btn-outline-danger m-btn m-btn--pill m-btn--wide btn-sm">
																Submit
															</a>
														</li>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- END: Subheader -->
					<div class="m-content">
						<div class="row">
							<div class="col-lg-12">
								<!--begin::Portlet-->
								<div class="m-portlet">
									<div class="m-portlet__head">
										<div class="m-portlet__head-caption">
											<div class="m-portlet__head-title">
												<span class="m-portlet__head-icon m--hide">
													<i class="la la-gear"></i>
												</span>
												
											</div>
										</div>
									</div>
									<!--begin::Form-->
									
									<form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" method="POST" action="{{route('subject_categories.update', ['id' => $sub_cat->id])}}" enctype="multipart/form-data">
                       				 {{ csrf_field() }}
                       				 {{ method_field('PATCH') }} 
										<div class="m-portlet__body">
											<div class="form-group m-form__group row">
													<div class="col-lg-6">
													<label>
														NameEN:
													</label>
													<input type="text" class="form-control m-input" placeholder="Enter name" name="name_en" value="{{$sub_cat->name_en}}" required>
													<span class="m-form__help">
														Please enter name_en
													</span>
												</div>
												<div class="col-lg-6">
													<label>
														NameAR:
													</label>
													<input type="text" class="form-control m-input" placeholder="Enter name" name="name_ar" value="{{$sub_cat->name_ar}}" required>
													<span class="m-form__help">
														Please enter name_ar
													</span>
												</div>


												<div class="col-lg-6">
													<label>
														Image:
													</label>
													<img src="{{asset($sub_cat->image)}}" width="155px">
													<input type="file" class="form-control m-input" placeholder="Enter your image" name="image" required>
													<span class="m-form__help">
														Please upload your image
													</span>
												</div>

												<div class="col-lg-6">
													<label class="">
														Type
													</label>
													<div class="m-input-icon m-input-icon--right">
														<select name="type_id" id="parent_category" class="form-control m-input  m-input--square" required>
						                                    @foreach ($types as $type )
						                                        <option value="{{ $type->id }}" @if ($type->id==$sub_cat->type_id)
					                                               selected 
					                                           @endif>{{ $type->name_en.'_'.$type->name_ar }}</option>
						                                    @endforeach
						                                </select>
													</div>
													<span class="m-form__help">
														Please enter Type
													</span>
												</div> 
												
											</div>
											
											
										</div>
										<div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
											<div class="m-form__actions m-form__actions--solid">
												<div class="row">
													<div class="col-lg-6">
														<button type="Submit" class="btn btn-brand">
															Save
														</button>
														<a type="button" class="btn btn-default" href="{{route('subject_categories.index')}}" style="color: #716aca;">
															Cancel
														</a>
													</div>
													<div class="col-lg-6 m--align-right">
														<button type="reset" class="btn btn-danger">
															Delete
														</button>
													</div>
												</div>
											</div>
										</div>
									</form>
									<!--end::Form-->
								</div>
								<!--end::Portlet-->
							</div>
						</div>
					</div>
				</div>



@endsection